async (page) => {
  const browser = page.context().browser();
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, serviceWorkers: "block" });
  const p = await context.newPage();
  const errors = [], checks = [];
  const check = (name, value) => { checks.push({ name, ok: !!value }); if (!value) throw new Error(name); };
  p.on("pageerror", e => errors.push(e.message));
  p.on("dialog", d => d.accept());
  try {
    await p.goto("http://127.0.0.1:8793/");
    await p.waitForFunction(() => typeof experienceInitialized !== "undefined" && experienceInitialized);
    await p.evaluate(() => {
      closeModal(); S.tutoDone = true; S.players = [newPlayer("REAL GAME")]; S.notes = "Preserve real notes"; save();
      window.originalRaw = localStorage.getItem(STORE_KEY); startTestGame();
    });
    await p.locator("#g-layout").click();
    check("mobile GM list", await p.locator("#gm-list").count() === 1);
    check("mobile dock absent", await p.locator("#dock").evaluate(e => getComputedStyle(e).display === "none"));
    await p.evaluate(() => openSeatModal(S.players.find(p => p.roleId === "chef").id));
    await p.locator("#s-isdrunk").click();
    check("Drunk actual and believed roles", await p.evaluate(() => S.players[1].roleId === "drunk" && S.players[1].shownRoleId === "chef" && assignedTeamCounts().outsider === 1));
    await p.locator("#s-reveal").click();
    const roleScreen = await p.locator("#xp-player-screen").innerText();
    check("role screen conceals actual Drunk", roleScreen.includes("Cuisinier") && !roleScreen.includes("Ivrogne"));
    await p.locator("#xp-player-screen button").click();
    check("neutral screen before return", (await p.locator("#xp-player-screen").innerText()).includes("Retour au Conteur"));
    await p.locator("#xp-player-screen button").click();
    await p.evaluate(() => { closeModal(); switchView("night"); });
    check("Drunk wakes as Chef", await p.locator('.night-step[data-key="char:chef"]').count() === 1);
    check("impaired info permits truth", (await p.locator('.night-step[data-key="char:chef"]').innerText()).includes("correcte ou incorrecte"));
    await p.evaluate(() => { S.bluffs = ["mayor", "slayer", "butler"]; save(); renderNight(); });
    await p.locator("[data-bluff-show]").click();
    const bluffs = await p.locator("#xp-player-screen").innerText();
    check("private bluff screen only intended values", bluffs.includes("Maire") && bluffs.includes("Majordome") && !bluffs.includes("Empoisonneur"));
    check("private screen makes grimoire inert", await p.locator("#app").evaluate(e => e.inert));
    await p.keyboard.press("g");
    check("private screen blocks shortcuts", await p.locator("#xp-player-screen").count() === 1);
    await p.locator("#xp-player-screen button").click();
    await p.locator("#xp-player-screen button").click();
    await p.evaluate(() => openReminderPicker(S.players.find(p => p.roleId === "empath").id, "poisoner", 0));
    await p.locator("#rem-apply").click();
    check("sourced poison applied", await p.evaluate(() => S.players.find(p => p.roleId === "empath").statuses.poisoned));
    await p.evaluate(() => { GameCore.setManualStatus(S.players.find(p => p.roleId === "poisoner"), "drunk", true); openReminderPicker(S.players.find(p => p.roleId === "monk").id, "poisoner", 0); });
    check("impaired source cannot apply effect", await p.locator("#rem-effect").isDisabled());
    await p.locator("#rem-choice").click();
    check("simulated choice has no poison effect", await p.evaluate(() => !S.players.find(p => p.roleId === "monk").statuses.poisoned));
    await p.getByRole("button", { name: "Guidé", exact: true }).click();
    check("guided night shows one step", await p.locator(".night-step:visible").count() === 1);
    const firstKey = await p.evaluate(() => S.night.focusKey);
    await p.getByRole("button", { name: "Suivant →", exact: true }).click();
    check("guided next changes focused step", await p.evaluate(key => S.night.focusKey !== key, firstKey));
    await p.evaluate(() => { S.phase = "day"; S.day.number = 1; S.day.nominations = []; S.day.execution = null; switchView("day"); });
    await p.locator("#d-nom").click();
    const people = await p.evaluate(() => S.players.map(p => p.id));
    await p.locator("#nom-nominee").selectOption(people[2]);
    await p.locator("#nom-nominator").selectOption(people[0]);
    await p.locator("#nom-ok").click();
    await p.evaluate(() => { S.day.nominations[0].votes = 4; save(); renderDay(); });
    check("nomination threshold frozen", await p.evaluate(() => S.day.nominations[0].threshold === 4));
    await p.locator("[data-exec]").click();
    await p.locator("#exec-death").selectOption("survives");
    await p.locator("#exec-confirm").click();
    check("execution may survive", await p.evaluate(() => S.day.execution && !S.day.execution.died && S.players[2].alive));
    check("second execution is blocked", await p.locator("#d-manual-exec").isDisabled());
    await p.evaluate(() => { undo(); S.players[6].alive = false; announceEndIfAny(); });
    check("candidate end does not auto-celebrate", await p.locator(".end-overlay").count() === 0);
    await p.evaluate(() => { switchView("scripts"); });
    const script = await p.evaluate(() => S.scriptId);
    await p.locator('[data-ref="bad-moon-rising"]').click();
    check("browsing another script leaves game intact", await p.evaluate(id => S.scriptId === id, script));
    await p.evaluate(() => { openMessageComposer(S.players[0].id); });
    const composerInputs = await p.locator("#modal").innerText();
    check("private message composer accessible", composerInputs.includes("Type d’information"));
    await p.evaluate(() => { closeModal(); openSetupChecklist(); });
    check("preparation checklist accessible", (await p.locator("#modal").innerText()).includes("Voyante"));
    await p.evaluate(() => { closeModal(); setLang("en"); openSetupChecklist(); });
    check("checklist English", (await p.locator("#modal").innerText()).includes("Fortune Teller"));
    await p.evaluate(() => { closeModal(); switchView("grimoire"); });
    check("training never wrote real game", await p.evaluate(() => localStorage.getItem(STORE_KEY) === window.originalRaw));
    check("mobile no horizontal overflow", await p.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await p.locator("#exit-training").click();
    await p.waitForFunction(() => typeof S !== "undefined" && S.players[0]?.name === "REAL GAME");
    check("return restores real game", await p.evaluate(() => !TRAINING && S.notes === "Preserve real notes"));
    const second = await context.newPage();
    await second.goto("http://127.0.0.1:8793/");
    await second.waitForFunction(() => typeof READ_ONLY !== "undefined" && READ_ONLY);
    await second.locator("#storage-warning").waitFor({ state: "visible" });
    check("second real tab protected", await second.locator("#storage-warning").isVisible());
    check("no browser exceptions", errors.length === 0);
    return { checks, errors };
  } finally {
    await context.close();
  }
}
